[package]
name = "chapa-rust"
version = "0.1.0"
edition = "2024"
description = "Chapa SDK for Rust to integrate Chapa payment gateway into your Rust applications."

authors = [
  "Abenezer Haymanot <@abeni-csa> [abenzerhaymanot@gmail.com]",
  "YabetsZ  <@YabetsZ> [yabetszekaryas07@gmail.com]",
]

license = "MIT"

repository = "https://github.com/Chapa-Et/chapa-rust"

homepage = "https://developer.chapa.co/"

# documentation = "https://docs.rs/chapa-rust" # Not realeased yet

readme = "README.md"

keywords = ["chapa", "rust-sdk", "payment", "gateway"]

categories = [
  "api-bindings",
  "asynchronous",
  "web-programming::http-client",
  "finance",
  "development-tools::api",
]

[[test]]
name = "tests"
path = "tests/mod.rs"
# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
reqwest = { version = "0.12.24", features = ["json"] }
serde = { version = "1.0", features = ["derive"] }
thiserror = "2.0.17"
dotenvy = "0.15.7"
chrono = { version = "0.4.42", features = ["serde"] }
serde_json = "1.0.145"

[dev-dependencies]
tokio = { version = "1", features = ["full"] }
mockito = "1.7.0"

[package.metadata.docs.rs]
all-features = true
